export { default as BigCard } from './BigCard'
export { default as CorrectBox } from './CorrectBox'
export { default as GenerateButton } from './GenerateButton'
export { default as GeneratedResultsBox } from './GeneratedResultsBox'
export { default as InputBox } from './InputBox'
export { ConfigModal, FirstModal, InstructionModal } from './Modal'
export { default as SmallCard } from './SmallCard'
